### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by samcayford** [jpcx/node-kraken-api#2]
I have 2 instances of an object that use this library with different api key/secret. It seems the 2nd instance overwrites the settings for the first.
So, for example, if I get balances I always get the values from the account that was initialized last even though the `api/kraken` object is initialized with different key/secret.

**Comment by jpcx** [comment]
Hello, thank you for raising this issue! Apologies for not replying sooner. I ended up rewriting it and the new version should not have this issue. If you're upgrading please see the release notes.
