### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by EricCrosson** [jpcx/node-kraken-api#3]
Howdy,

Sweet project! I'm just now checking it out, and have to say it would be much easier to prototype with some static TypeScript types. 

Not sure if this repository is actively maintained (last commit 3 years ago), if not then [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) would be the best option forward

Opening this issue to track interest and any effort towards this goal

**Comment by jpcx** [comment]
Hello, thanks for the suggestion! I completely agree; I ended up rewriting the whole project in TypeScript :-).
