### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by Kaexburli** [jpcx/node-kraken-api#6]
Hello,

For a few days I have been receiving an error on my code which has been working for some time and I cannot find what is causing the problem

Using the exportStatus method I have a return EGeneral:Invalid arguments

the only arguments is a string report, I hardly see how I can be wrong on this arguments

here is my test code (is the same on my original code):

```
import { Kraken } from 'node-kraken-api'

const apikey = {
  pubKey: '************.....',
  privKey: '************.....',
}

const apiKraken = new Kraken({
  key: apikey.pubKey,
  secret: apikey.privKey
});

(async () => {
  try {
    const balance = await apiKraken.balance();
    console.log(balance) // Good
    const status = await apiKraken.exportStatus({ report: "ledgers" });
    console.log(status) // Error
  } catch (error) {
    console.error(error)
  }
})();

```

This is the returned error:

```
PS tests> node .\test.js
RESTAPIError: ["EGeneral:Invalid arguments"]
    at _UTF8Receiver.finalize (node_modules\node-kraken-api\index.js:915:23)
    at IncomingMessage.<anonymous> (node_modules\node-kraken-api\index.js:1081:21)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  body: { error: [ 'EGeneral:Invalid arguments' ] }

```

I specify that I made several tests with the same code by asking balance for example and using another api key, the code works well for balance and my file is saved in UTF8

Thank you for the time to see if on your side the error is also returned

**Comment by jpcx** [comment]
Hello, thank you for letting me know about this! I did experiments and figured out that the `ExportStatus` endpoint requires the `Content-Type` header to be set to `"application/x-www-form-urlencoded"`.

I've added the `Content-Type` header to the REST request function and your example now works!
You should be able to install version 2.2.0 it from NPM.

**Comment by jpcx** [comment]
Hello, thank you for letting me know about this! I did experiments and figured out that the `ExportStatus` endpoint requires the `Content-Type` header to be set to `"application/x-www-form-urlencoded"`.

I've added the `Content-Type` header to the REST request function and your example now works!
You should be able to install version 2.2.0 it from NPM.

**Comment by Kaexburli** [comment]
Hi,

it's work perfectly after update!

Thank you very much
